export const ImagePath = {
  SIGNUPNO: require("../assets/Images/SignUp/Signupu.png"),
  SIGNUPNOD: require("../assets/Images/SignUp/SignupMask.png"),
  BUTTON: require("../assets/Images/SignUp/Button.png"),
  OTP: require("../assets/Images/SignUp/Otp.png"),
  OTPMASK: require("../assets/Images/SignUp/OtpMask.png"),
  CONFRMMASK: require("../assets/Images/SignUp/ConfirmMask.png"),
  CONFRM: require("../assets/Images/SignUp/VerifyU.png"),
  THANKS: require("../assets/Images/SignUp/Thanks.png"),
  BACKARROW: require("../assets/Images/SignUp/Backarrow.png"),
  CHECK: require("../assets/Images/SignUp/Check.png"),
  UNCHECK: require("../assets/Images/SignUp/checkmark.png"),
  FRAME: require("../assets/Images/SignUp/Frame.png"),
  FRAMEMASK: require("../assets/Images/SignUp/FrameMask.png"),
  HIDE: require("../assets/Images/SignUp/Hide.png"),
  SHOW: require("../assets/Images/SignUp/visibility.png"),
  APPLE: require("../assets/Images/SignUp/Apple.png"),
  FB: require("../assets/Images/SignUp/Facebook.png"),
  GOOGLE: require("../assets/Images/SignUp/Google.png"),

  // ============ Bottom Tab ================= // 
  BASE: require("../assets/Images/BottomTab/Base.png"),
  CARDOFF: require("../assets/Images/BottomTab/Card.png"),
  MARKETOFF: require("../assets/Images/BottomTab/MarketOff.png"),
  REWARDOFF: require("../assets/Images/BottomTab/Reward.png"),
  WALLETON: require("../assets/Images/BottomTab/WalletOn.png"),
  BOTTOMTABBACK: require("../assets/Images/BottomTab/BottomTabBack.png"),


  // ============ Wallet Header ================= // 
  // BACKHEADER: require("../assets/Images/Header/HeaderBack.png"),
  BACKHEADER: require("../assets/Images/Header/HeaderBackNew.png"),
  BACKICON: require("../assets/Images/Header/Backicon.png"),
  BANK: require("../assets/Images/Header/Bank.png"),
  DRAWER: require("../assets/Images/Header/Drawer.png"),
  FAQ: require("../assets/Images/Header/Faq.png"),
  CROSSHEAD: require("../assets/Images/Header/CrossHead.png"),

  // ============  Header ================= // 
  HEADERBACK: require("../assets/Images/HeaderTwo/HeaderBackTwo.png"),


  // ============  Pay ================= // 
  ADBACK: require("../assets/Images/Pay/Adback.png"),
  AIR: require("../assets/Images/Pay/Air.png"),
  BTN: require("../assets/Images/Pay/Btn.png"),
  BUTTONBACK: require("../assets/Images/Pay/Buttonback.png"),
  FORWARD: require("../assets/Images/Pay/Forward.png"),
  GIFT: require("../assets/Images/Pay/Gift.png"),
  HAT: require("../assets/Images/Pay/Hat.png"),
  PLAY: require("../assets/Images/Pay/Play.png"),
  RECIEVEICON: require("../assets/Images/Pay/Recieve.png"),
  SCAN: require("../assets/Images/Pay/Scan.png"),
  SENDICON: require("../assets/Images/Pay/Send.png"),
  SENDBTNICON: require("../assets/Images/Pay/SendBtn.png"),
  WATCH: require("../assets/Images/Pay/Watch.png"),
  HATBACK: require("../assets/Images/Pay/HatBack.png"),
  BUFFER: require("../assets/Images/Pay/Buffering.png"),
  DOWNLOAD: require("../assets/Images/Pay/Download.png"),
  NETWORK: require("../assets/Images/Pay/Network.png"),
  WALLET: require("../assets/Images/Pay/Wallet.png"),
  WITHDRAWBACK: require("../assets/Images/Pay/WithdrawBack.png"),
  CLOSE: require("../assets/Images/Pay/Close.png"),
  OPTIONBACK: require("../assets/Images/Pay/Optionback.png"),
  LOGOBACK: require("../assets/Images/Pay/Logoback.png"),
  PAYBACK: require("../assets/Images/Pay/PayBack.png"),


  // ============  Market ================= // 
  BITCOINB: require("../assets/Images/Market/BitcoinB.png"),
  LISTBACK: require("../assets/Images/Market/Listback.png"),
  NEWSBACK: require("../assets/Images/Market/Newsback.png"),
  MODALCLOSE: require("../assets/Images/Market/Modalclose.png"),
  P2P: require("../assets/Images/Market/P2p.png"),
  SWAP: require("../assets/Images/Market/Swap.png"),
  TRADEBACK: require("../assets/Images/Market/Tradeback.png"),
  TRADING: require("../assets/Images/Market/Trading.png"),
  MARKETUP: require("../assets/Images/Market/Marketup.png"),
  MARKETDOWN: require("../assets/Images/Market/Marketdown.png"),
  CATEGORYBACK: require("../assets/Images/Market/Categoryback.png"),
  BELL: require("../assets/Images/Market/Bell.png"),
  CALENDER: require("../assets/Images/Market/Calender.png"),
  CALENDERBACK: require("../assets/Images/Market/Calenderback.png"),
  EXPLORERBACK: require("../assets/Images/Market/Explorersback.png"),
  GRAPH: require("../assets/Images/Market/Graph.png"),
  HRBACK: require("../assets/Images/Market/Hrback.png"),
  ICONBACK: require("../assets/Images/Market/Iconback.png"),
  MARKETHEADER: require("../assets/Images/Market/MarketHeaderback.png"),
  RECURRINGBACK: require("../assets/Images/Market/Recurringback.png"),
  STAR: require("../assets/Images/Market/Star.png"),
  RATINGBAR: require("../assets/Images/Market/Ratingbar.png"),
  COINFORWARD: require("../assets/Images/Market/Coinarrow.png"),
  INSUFBACK: require("../assets/Images/Market/InsufBack.png"),
  CLOCK: require("../assets/Images/Market/Clock.png"),
  CLOCKBACK: require("../assets/Images/Market/Clockback.png"),
  ADDBTN: require("../assets/Images/Market/Addbtn.png"),
  MASTERCARD: require("../assets/Images/Market/Mastercard.png"),
  CARDOTPIMG: require("../assets/Images/Market/CardOtp.png"),



  // ============ Drawer ================= // 
  HEAD: require("../assets/Images/Drawer/DrawerHead.png"),
  AVATAR: require("../assets/Images/Drawer/Avatar.png"),
  BUY: require("../assets/Images/Drawer/Buy.png"),
  CROSS: require("../assets/Images/Drawer/Cross.png"),
  DRAWERBACK: require("../assets/Images/Drawer/DrawerBack.png"),
  EARN: require("../assets/Images/Drawer/Earn.png"),
  MAINBACK: require("../assets/Images/Drawer/Mainback.png"),
  REFER: require("../assets/Images/Drawer/Refer.png"),
  WALLETDRAWER: require("../assets/Images/Drawer/WalletDrawer.png"),
  CREDIT: require("../assets/Images/Drawer/Credit.png"),
  MARKET: require("../assets/Images/Drawer/Market.png"),
  PAY: require("../assets/Images/Drawer/Pay.png"),
  REWARD: require("../assets/Images/Drawer/Reward.png"),
  SETTING: require("../assets/Images/Drawer/Setting.png"),



  // ============ Wallet ================= // 
  DOLLAR: require("../assets/Images/Home/Dollar.png"),
  DOWN: require("../assets/Images/Home/Down.png"),
  RECIEVE: require("../assets/Images/Home/Recieve.png"),
  SEARCH: require("../assets/Images/Home/Search.png"),
  SEND: require("../assets/Images/Home/Send.png"),
  TRADE: require("../assets/Images/Home/Trade.png"),
  GROW: require("../assets/Images/Home/Grow.png"),
  UP: require("../assets/Images/Home/Up.png"),
  CROSSBLUE: require("../assets/Images/Home/CrossBlue.png"),
  BACKGROUNDCONTACT: require("../assets/Images/Home/Contactback.png"),
  BLOCK: require("../assets/Images/Home/Block.png"),
  // CROSS: require("../assets/Images/Home/CrossBlue.png"),

  // ============ COINS ================= // 
  BITCOIN: require("../assets/Images/Coins/Bitcoin.png"),
  BNG: require("../assets/Images/Coins/Bng.png"),
  ETH: require("../assets/Images/Coins/Etherium.png"),
  TTH: require("../assets/Images/Coins/Tether.png"),

  // ============ Recieve ================= // 
  QR: require("../assets/Images/HeaderTwo/Qrcode.png"),

  // ============ Send ================= // 
  ADD: require("../assets/Images/SendBitcoins/Add.png"),
  OPTION: require("../assets/Images/SendBitcoins/Option.png"),
  PROFILE: require("../assets/Images/SendBitcoins/Profile.png"),
  DETAILBACK: require("../assets/Images/SendBitcoins/DetailBack.png"),
  DOWNING: require("../assets/Images/SendBitcoins/DropDown.png"),
  SUCCESS: require("../assets/Images/SendBitcoins/Sucess.png"),

  // ============ Gift ================= // 
  AMAZON: require("../assets/Images/Gift/Amazon.png"),
  APPLE: require("../assets/Images/Gift/Apple.png"),
  BRANDBACK: require("../assets/Images/Gift/BrandBack.png"),
  CATEGORY: require("../assets/Images/Gift/Category.png"),
  DOWNARROW: require("../assets/Images/Gift/Downarrow.png"),
  FLIPKART: require("../assets/Images/Gift/Flipkart.png"),
  GIFTCCARDS: require("../assets/Images/Gift/Gift.png"),
  META: require("../assets/Images/Gift/Meta.png"),
  MSN: require("../assets/Images/Gift/Msn.png"),
  SHOP: require("../assets/Images/Gift/Shope.png"),
  WINDOWS: require("../assets/Images/Gift/Windows.png"),
  FUNDSBACK: require("../assets/Images/Gift/FundsBack.png"),
  CASH: require("../assets/Images/Gift/Cash.png"),
  DOLLARBACK: require("../assets/Images/Gift/DollarBack.png"),
  DOLLARSIGN: require("../assets/Images/Gift/DollarSign.png"),
  MOBILE: require("../assets/Images/Gift/Mobile.png"),
  PAYEER: require("../assets/Images/Gift/Payeer.png"),
  PAYMENTBACK: require("../assets/Images/Gift/PayementBack.png"),
  SELECT: require("../assets/Images/Gift/Select.png"),
  UNSELECT: require("../assets/Images/Gift/Unselect.png"),
  USD: require("../assets/Images/Gift/Usd.png"),

  // ============ Reward ================= // 
  ADDINGBUTN: require("../assets/Images/Reward/Addbtn.png"),
  COPY: require("../assets/Images/Reward/Copy.png"),
  COPYBACK: require("../assets/Images/Reward/Copyback.png"),
  INVITE: require("../assets/Images/Reward/Invitewhatsapp.png"),
  LIKE: require("../assets/Images/Reward/Like.png"),
  LIKEBACK: require("../assets/Images/Reward/Likeback.png"),
  PRICE: require("../assets/Images/Reward/Price.png"),
  QUESTIONBACK: require("../assets/Images/Reward/Questionback.png"),
  QUESTIONBACKING: require("../assets/Images/Reward/Questionbacking.png"),
  QUESTIONMARK: require("../assets/Images/Reward/Questionmark.png"),
  REWARDBACK: require("../assets/Images/Reward/Rewardback.png"),
  REWARDTYPE: require("../assets/Images/Reward/RewardType.png"),
  SHARE: require("../assets/Images/Reward/Share.png"),
  TOTALEARNED: require("../assets/Images/Reward/Totalearnedback.png"),
  TOTALEARNEDR: require("../assets/Images/Reward/TotalearnedbackR.png"),
  REFERALLISTBACK: require("../assets/Images/Reward/ReferalListBack.png"),


  // ============ Card ================= // 
  CARDBACK: require("../assets/Images/Card/Cardback.png"),
  CARDBTN: require("../assets/Images/Card/Cardbtn.png"),
  CARDNEW: require("../assets/Images/Card/CardNew.png"),
  CARDOLD: require("../assets/Images/Card/CardOld.png"),
  REVIEW: require("../assets/Images/Card/Review.png"),
  VCARD: require("../assets/Images/Card/VCard.png"),
  CARDLISTBACK: require("../assets/Images/Card/listBack.png"),
  PERCENT: require("../assets/Images/Card/PercentView.png"),
  TICK: require("../assets/Images/Card/Tick.png"),
  FORWARDARROW: require("../assets/Images/Card/Forward.png"),
  DESLECT: require("../assets/Images/Card/Unselect.png"),
  SECONDLISTBACK: require("../assets/Images/Card/SecondListBack.png"),


  // ============ Ashish1 ================= // 
  SIGNUPNO: require("../assets/Images/SignUp/Signupu.png"),
  SIGNUPNOD: require("../assets/Images/SignUp/SignupMask.png"),
  BUTTON: require("../assets/Images/SignUp/Button.png"),
  OTP: require("../assets/Images/SignUp/Otp.png"),
  OTPMASK: require("../assets/Images/SignUp/OtpMask.png"),
  CONFRMMASK: require("../assets/Images/SignUp/ConfirmMask.png"),
  CONFRM: require("../assets/Images/SignUp/VerifyU.png"),
  THANKS: require("../assets/Images/SignUp/Thanks.png"),
  BACKARROW: require("../assets/Images/SignUp/Backarrow.png"),
  CHECK: require("../assets/Images/SignUp/Check.png"),
  UNCHECK: require("../assets/Images/SignUp/checkmark.png"),
  FRAME: require("../assets/Images/SignUp/Frame.png"),
  FRAMEMASK: require("../assets/Images/SignUp/FrameMask.png"),
  HIDE: require("../assets/Images/SignUp/Hide.png"),
  SHOW: require("../assets/Images/SignUp/visibility.png"),
  APPLE: require("../assets/Images/SignUp/Apple.png"),
  FB: require("../assets/Images/SignUp/Facebook.png"),
  GOOGLE: require("../assets/Images/SignUp/Google.png"),
  SPLASH1: require("../assets/Images/Splash/Splash1/Splash1.png"),
  SPLASH2: require("../assets/Images/Splash/Splash2/Splash2.png"),
  SPLASH3: require("../assets/Images/Splash/Splash3/Splash3.png"),
  MIRRORSPALSH1: require("../assets/Images/Splash/MirrorSplash1/MirrorSplash1.png"),
  MIRRORSPALSH2: require("../assets/Images/Splash/MirrorSplash2/MirrorSplash2.png"),
  MIRRORSPALSH3: require("../assets/Images/Splash/MirrorSplash3/MirrorSplash3.png"),
  SPLASHBACKGROUND: require("../assets/Images/Splash/SplashBackground/SplashBackground.png"),
  BACKARROW: require("../assets/Images/Splash/Arow/Arow.png"),
  SMALLBUTTON: require("../assets/Images/Splash/SmallButton/SmallButton.png"),
  CREATACCOUNT_LOGO: require("../assets/Images/LoginImage/Creactaccount/Createaccount.png"),
  CREATACCOUNT_MIRROR_LOGO: require("../assets/Images/LoginImage/Createaccountmirror/Createaccountmirror.png"),
  MASK_SIGNUP: require("../assets/Images/LoginImage/Masksignup/Masksignup.png"),
  REFERRAL_CODE: require("../assets/Images/LoginImage/Referralcode/Referralcode.png"),
  REFERRAL_CODE_MIRROR: require("../assets/Images/LoginImage/Referralcodemirror/Referralcodemirror.png"),
  SIGNUP1: require("../assets/Images/LoginImage/Signup1/Signup1.png"),
  SIGNUP1_MIRROR: require("../assets/Images/LoginImage/Signupmirror/Signupmirror.png"),
  // KYC_BACK_BUTTON: require("../assets/Images/kyc/backbutton/backbutton.png"),
  // NEXT_ARROW: require("../assets/Images/kyc/nextArow/nextArow.png"),

  SELFE: require("../assets/Images/kyc/Selfe/Selfe.png"),
  USER_BUTTON_BG: require("../assets/Images/kyc/UserButtonbg/UserButtonbg.png"),
  USER_ICONE: require("../assets/Images/kyc/UserIcon/UserIcon.png"),
  ID_ICONE: require("../assets/Images/kyc/IdIcon/IdIcon.png"),

  CONTENT_WRITE: require("../assets/Images/kyc/contentwrite/contentwrite.png"),
  BLURRY_IMAGE: require("../assets/Images/kyc/BlurryImage/BlurryImage.png"),
  FOLDED_WRUNKEL: require("../assets/Images/kyc/FoldedWrunkel/FoldedWrunkel.png"),
  HAND_WRITING: require("../assets/Images/kyc/HandWriting/HandWriting.png"),
  PHOTO_ID: require("../assets/Images/kyc/PhotoID/PhotoID.png"),
  KYC_BACK_BUTTON: require("../assets/Images/kyc/backbutton/backbutton.png"),
  NEXT_ARROW: require("../assets/Images/kyc/nextArow/nextArow.png"),
  BANK_ICONE: require("../assets/Images/setting/bankIcone/bankIcone.png"),
  SELFE: require("../assets/Images/kyc/Selfe/Selfe.png"),
  USER_BUTTON_BG: require("../assets/Images/kyc/UserButtonbg/UserButtonbg.png"),
  USER_ICONE: require("../assets/Images/kyc/UserIcon/UserIcon.png"),
  ID_ICONE: require("../assets/Images/kyc/IdIcon/IdIcon.png"),
  NAMEBACK: require("../assets/Images/kyc/IDcard/nameback.png"),
  CONTENT_WRITE: require("../assets/Images/kyc/contentwrite/contentwrite.png"),
  BLURRY_IMAGE: require("../assets/Images/kyc/BlurryImage/BlurryImage.png"),
  FOLDED_WRUNKEL: require("../assets/Images/kyc/FoldedWrunkel/FoldedWrunkel.png"),
  HAND_WRITING: require("../assets/Images/kyc/HandWriting/HandWriting.png"),
  PHOTO_ID: require("../assets/Images/kyc/PhotoID/PhotoID.png"),
  SIGNUP_PHONE: require("../assets/Images/kyc/SignUpPhone/SignUpPhone.png"),
  SIGNUP_PHONE_MIRROR: require("../assets/Images/kyc/SignUpPhoneMirror/SignUpPhoneMirror.png"),
  // BRW: require("../assets/Images/countryimages/"),
  SELECT_ID_BG: require("../assets/Images/kyc/SelectIdBg/SelectIdBg.png"),
  IDHEAD: require("../assets/Images/kyc/IDcard/Idhead.png"),
  PASSPORT: require("../assets/Images/kyc/Passport/Passport.png"),
  ID_CARD_IMAGE: require("../assets/Images/kyc/IDcard/IDcard.png"),
  DRIVING_LICENCE: require("../assets/Images/kyc/DrevingLicence/DrevingLicence.png"),
  SCAN_DOUMENT_BG: require("../assets/Images/kyc/ScanDocumentBg/ScanDocumentBg.png"),
  PASSPORTBG: require("../assets/Images/kyc/Passportbg/Passportbg.png"),
  TBG: require("../assets/Images/Splash/TBG.png"),
  SPLASH_BG: require("../assets/Images/Splash/SplasBG.png"),
  BASE_REWARD: require("../assets/Images/Splash/BaseReward/BaseReward.png"),
  SCANNER: require("../assets/Images/kyc/Scanner/Scanner.png"),
  DOCUMENT_VERIFIED: require("../assets/Images/kyc/DocumentVerfiedSuccess/DocumentVerfiedSuccess.png"),
  VERIFICATION_PENDING: require("../assets/Images/kyc/VerificationPending/VerificationPending.png"),
  SCANE: require("../assets/Images/kyc/Scan/Scan.png"),
  GIRL: require("../assets/Images/kyc/Girl/Girl.png"),
  GIRL_FACE: require("../assets/Images/kyc/GirlFace/GirlFace.png"),
  BRW: require("../assets/Images/Splash/Brw/Brw.png"),
  BRW_MIRROR: require("../assets/Images/Splash/BrwMirror/BrwMirror.png"),
  BRW_BG: require("../assets/Images/Splash/brwBg.png"),
  NXT_ICONE: require("../assets/Images/setting/Nxticon/Nxticon.png"),
  PFL_BG: require("../assets/Images/setting/profileBg/profileBg.png"),
  BNK_BG: require("../assets/Images/setting/BankBg/BankBg.png"),
  CNT_BG: require("../assets/Images/setting/CntBG/CntBG.png"),
  PPGIRL: require("../assets/Images/setting/profilePhotoGirl/profilePhotoGirl.png"),
  PRC: require("../assets/Images/setting/Prc/Prc.png"),
  PRC_PEN: require("../assets/Images/setting/prcPen/prcPen.png"),

  THREE_DOT: require("../assets/Images/setting/threedot/threedot.png"),
  BANK_PHOTOS: require("../assets/Images/setting/Bankphoto/Bankphoto.png"),

  HOME_CIRCLE: require("../assets/Images/setting/homeCircle/homeCircle.png"),
  HOME_ICONE: require("../assets/Images/setting/HomeIcon/HomeIcon.png"),
  WALLET_IMG: require("../assets/Images/setting/Walletimg/Walletimg.png"),
  WHITE_CIRCLE: require("../assets/Images/setting/whitecircle/whitecircle.png"),
  WININD_BETCH: require("../assets/Images/setting/wining/wining.png"),
  INSTALL: require("../assets/Images/setting/install/install.png"),
  SCANN: require("../assets/Images/setting/scann/scann.png"),
  QR_CODE: require("../assets/Images/setting/QrCode/QrCode.png"),
  COPY_ICONE: require("../assets/Images/setting/CopyImage/CopyImage.png"),
  SLAT_ICONE: require("../assets/Images/setting/Slat/Slat.png"),
  VISITE_ICON: require("../assets/Images/setting/VisitIcon/VisitIcon.png"),
  MOBILE_ICONE: require("../assets/Images/setting/mobileIcon/mobileIcon.png"),
  CONTECT_BG: require("../assets/Images/setting/ContectBG.png"),
  // HELP: require("../assets/Images/setting/help/help.png"),
  CONVER_BG: require("../assets/Images/setting/converBg/converBg.png"),
  TELI: require("../assets/Images/setting/Teli/Teli.png"),
  TIMER: require("../assets/Images/setting/Timer/Timer.png"),
  BTN_BG: require("../assets/Images/setting/btnBG/btnBG.png"),
  WALLETUNCHECK: require("../assets/Images/setting/WalletUncheck.png"),
  REWARDUNCHECK: require("../assets/Images/setting/RewardUncheck.png"),


  // ============ Ambrish ================= // 
  //==============CryptoEarnImages=========//
  TIC_MARK: require("../assets/Images/CryptoEarn/TikMark/TikMark.png"),
  DOWN_ARROW2: require("../assets/Images/CryptoEarn/downArrow2/downArrow2.png"),
  SELECT_TERMBG: require("../assets/Images/CryptoEarn/TermBG/TermBG.png"),
  CHECK_BG: require("../assets/Images/CryptoEarn/CheckBg/CheckBg.png"),
  CHECK_MARK: require("../assets/Images/CryptoEarn/CheckMark/CheckMark.png"),
  CHECKSQUARE_BG: require("../assets/Images/CryptoEarn/CheckSquareBg/CheckSquareBg.png"),
  UNTICKSQUARE_BG: require("../assets/Images/CryptoEarn/BorderSquareTick/BorderSquareTick.png"),
  UNTICKCIRCLE_BG: require("../assets/Images/CryptoEarn/CircleTickMark/CircleTickMark.png"),

};
