import {
  StyleSheet,
  Text,
  View,
  SafeAreaView,
  Dimensions,
  ImageBackground,
  Switch,
  TouchableOpacity,
  Image,
} from "react-native";
import React, { useState } from "react";
import { KeyboardAwareScrollView } from "react-native-keyboard-aware-scroll-view";
import { ImagePath } from "../../utils/ImagePath";
import { FONTS } from "../../utils/FontFamily";
import CustomButton from "../../components/Buttons/CustomButton";
const { height, width } = Dimensions.get("screen");
import Header from "../../components/Header/Header";
import { COLOR } from "../../utils/Colors";
import { TextInput } from "react-native-gesture-handler";
import CustomInput from "../../components/CustomInput/CustomInput";

const EnableFactor_Authentication = (props) => {
  const renderProfile = () => {
    return (
      <View
        style={{
          height: height * 0.7,
          width: width * 1,
          // backgroundColor: "red",
          //   borderWidth: 1,
          marginVertical: 25,
        }}
      >
        <View style={styles.requirePasscode}>
          <Text
            style={{
              fontFamily: FONTS.PoppinsMedium,
              fontSize: height / 50,
              color: "#2C3A4B",
            }}
          >
            Enter the 6-digit verification code{"\n"}
            generated by your authenticator app
          </Text>
        </View>

        <View style={styles.copy}>
          <View style={styles.copyTxxt}>
            <View style={styles.texxInput}>
              <TextInput placeholder="Enter your 2FA code" />
            </View>
          </View>
          <View style={styles.copyImg}>
            <Image
              source={ImagePath.SLAT_ICONE}
              resizeMode="contain"
              style={{ height: 25, width: 25 }}
            />
          </View>
        </View>
      </View>
    );
  };

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: "#FFFFFF" }}>
      <Header
        backIcon={true}
        onBackPress={() => props.navigation.goBack()}
        HeaderTitle={true}
        Title="2-Factor Authentication"
      />
      {renderProfile()}
      <View
        style={{
          position: "absolute",
          bottom: 10,
          justifyContent: "center",
          alignItems: "center",
          height: height * 0.1,
          width: width * 1,
        }}
      >
        <CustomButton
          title="Enable 2FA"
          ButtonPress={() => props.navigation.navigate("Settings")}
        />
      </View>
    </SafeAreaView>
  );
};

export default EnableFactor_Authentication;

const styles = StyleSheet.create({
  requirePasscode: {
    height: height * 0.17,
    width: width * 0.9,
    alignSelf: "center",
    // borderWidth:1,
    justifyContent: "center",
  },
  copy: {
    height: height * 0.07,
    width: width * 0.9,
    justifyContent: "center",
    alignSelf: "center",
    // borderWidth: 1,
    alignItems: "center",
    borderRadius: 10,
    flexDirection: "row",
    backgroundColor: "#F4F4F4",
  },
  copyTxxt: {
    height: height * 0.07,
    width: width * 0.7,
    justifyContent: "center",
    // alignItems: "center",
  },
  copyImg: {
    height: height * 0.07,
    width: width * 0.2,
    justifyContent: "center",
    alignItems: "center",
  },
  texxInput: {
    height: height * 0.07,
    width: width * 0.55,
    // borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
  },
});
